### ISSUE TITLE
Материалы к курсу, домашние задания

### ISSUE THREAD

**Issue by telezhnaya** [CSC-MobDev-2016/lesson1#20]
На странице любого курса около каждой лекции есть окошко "материалы".
Большая просьба прикладывать слайды лекций и примеры кода (который вы писали на паре) к лекции на сайте CSC. Иногда не получается прийти на занятие, а так можно пролистать и хоть примерно понять, что было пропущено, и наверстать это самостоятельно.

Спасибо :-)

**Comment by thevery** [comment]
Презентацию выложил, ДЗ продублирую, когда выложу на гитхаб.

**Comment by thevery** [comment]
Выложил всё по третьей лекции. Если чего-то не хватает - feel free to open another issue.
